version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
    garie-plugin:
        build: .
        privileged: true
        volumes:
            - ./src:/usr/src/garie-plugin/src:z
            - ./config.json:/usr/src/garie-plugin/config.json:z
            - /var/run/docker.sock:/run/docker.sock
            - /usr/bin/docker:/bin/docker
        ports:
            - 3000:3000
        environment:
            - HOST=influxdb
            - WIKI_APIKEY=3cb7a6c4c70ccf238530782588468b6b211c3403
            - WIKI_SERVER=https://taskman.devel4cph.eea.europa.eu/
            - WIKI_PAGE=Applications
            - WIKI_PROJECT=infrastructure
        depends_on:
            - influxdb

    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
